### ISSUE TITLE
Weird html report location

### ISSUE THREAD

**Issue by fweigl** [jaredsburrows/gradle-spoon-plugin#1]
Hi there, I replaced https://github.com/stanfy/spoon-gradle-plugin with your version (thanks by the way) of the Spoon client to run with Gradle 4.1. 

When I run `./gradlew spoonQaTestingReleaseAndroidTest`

(where `QaTesting` is a flavor and `Release` the build type)

the report is saved to: 

`/Users/myUsername/AndroidStudioProjects/my-project-name/app/build/Users/myUsername/AndroidStudioProjects/my-project-name/app/build/Users/myUsername/AndroidStudioProjects/my-project-name/app/build/spoon-output/stageRelease/productionRelease/qaTestingRelease/index.html`

I would expect the report to be at `/Users/myUsername/AndroidStudioProjects/my-project-name/app/build/spoon-output/qaTestingRelease/index.html`

Is this a bug in your Spoon implementation or a configuration problem on my end?

EDIT: When I add 

```
  spoon {
          output = "someDir"
        }
```

the report is saved there fine.

**Comment by fweigl** [comment]
Closing, since setting the output dir explicitly solves the issue.

**Comment by mweerasi** [comment]
Seems like this might be back in 2.0.0 snapshot
