### ISSUE TITLE
Builds fail due to transient snapshot dependency missing

### ISSUE THREAD

**Issue by savvasdalkitsis** [jaredsburrows/gradle-spoon-plugin#100]
Our builds are currently failing due to the spoon snapshot missing from the oss nexus repository:

https://oss.sonatype.org/content/repositories/snapshots/com/squareup/spoon/spoon-runner/2.0.0-SNAPSHOT/spoon-runner-2.0.0.pom

the manifest lists a lot of snapshot versions:

https://oss.sonatype.org/content/repositories/snapshots/com/squareup/spoon/spoon-runner/2.0.0-SNAPSHOT/maven-metadata.xml

Specific versions of the snapshot are available, for example:  

https://oss.sonatype.org/content/repositories/snapshots/com/squareup/spoon/spoon-runner/2.0.0-SNAPSHOT/spoon-runner-2.0.0-20181002.234303-49.pom

**Comment by jaredsburrows** [comment]
Are you still seeing this?

**Comment by jaredsburrows** [comment]
This build is working: https://github.com/jaredsburrows/gradle-spoon-plugin/actions/workflows/build.yml.
