### ISSUE TITLE
GStringImpl cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by hram** [jaredsburrows/gradle-spoon-plugin#12]
If I set instrumentationArgs in gradle file like this:

> instrumentationArgs = ["package:hram.testspoon.package1"]

all works correct

but I need to pass apguments from command line and if I add code like this

> if (project.hasProperty('spoonPackageName')) {
        instrumentationArgs = ["package:${project.getProperty('spoonPackageName')}"]
    }

then I have exception

> Caused by: java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
        at com.jaredsburrows.spoon.SpoonTask.spoonTask(SpoonTask.kt:111)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

Can you help me please?

**Comment by hram** [comment]
sorry my mistake

**Comment by hram** [comment]
I was thinking that is my mistake but I have this problem and can't fix this (

**Comment by hram** [comment]
I found workaround

> if (project.hasProperty('spoonPackageName')) {
        instrumentationArgs = ['package:' + project.spoonPackageName]
    }

**Comment by jaredsburrows** [comment]
@hram The latest Spoon snapshot from Square supports `instrumentationArgs = ["package:hram.testspoon.package1"]`. 

This DSL from the plugin supports both List and Map functionality. Are you still having this problem?

**Comment by hram** [comment]
the problem is how can I set params
if I set params like this

> instrumentationArgs = ['package:' + project.spoonPackageName]
all works fine

but if I sed like this

> instrumentationArgs = ["package:${project.getProperty('spoonPackageName')}"]
then I had error

**Comment by jaredsburrows** [comment]
What was the error? Both should work, here is a test I have that covers this: https://github.com/jaredsburrows/gradle-spoon-plugin/blob/master/src/test/groovy/com/jaredsburrows/spoon/SpoonPluginSpec.groovy#L60.

**Comment by jaredsburrows** [comment]
@hram Any update on this?

**Comment by jaredsburrows** [comment]
Since there is no response. I am going to close this for now.
