### ISSUE TITLE
Could not find com.xenomachina:kotlin-argparser:2.0.0.

### ISSUE THREAD

**Issue by fernandaalmeida** [jaredsburrows/gradle-spoon-plugin#121]
Im getting the following error on CI:
A problem occurred configuring project ':app'.
> Could not resolve all files for configuration ':app:classpath'.
   > Could not find com.xenomachina:kotlin-argparser:2.0.0.
     Searched in the following locations:
       - file:/home/runner/.m2/repository/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://dl.google.com/dl/android/maven2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://repo.maven.apache.org/maven2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://plugins.gradle.org/m2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
     Required by:
         project :app > com.jaredsburrows:gradle-spoon-plugin:1.6.0 > com.squareup.spoon:spoon-runner:2.0.0-SNAPSHOT:20181002.2[34](https://github.com/upday/android/actions/runs/3418929581/jobs/5691819034#step:3:35)303-49

I see there's no versions 2.0.0 on maven, just from 2.0.1. If this dependency from runner is not updated the lib cant be used anymore?

running dependencies:
- com.squareup.spoon:spoon-runner:2.0.0-SNAPSHOT
|    +--- com.squareup.spoon:spoon-common:2.0.0-SNAPSHOT
|    +--- com.squareup.spoon:spoon-internal-axmlparser:2.0.0-SNAPSHOT
|    +--- com.xenomachina:kotlin-argparser:2.0.0

Anyone had same issue? Could the dependency be upgraded?
Thanks

**Comment by cristiantanas** [comment]
We are facing the exact same issue in our team ... 
This only started happening a few days ago so probably this was removed recently from one of the sources.

In our case, as a workaround, we have added the Spring Plugins maven repo to the project as it seems that `com.xenomachina:kotlin-argparser:2.0.0` is still there. 

Nevertheless, it would be nice to have an official solution for this.

**Comment by jaredsburrows** [comment]
This looks like this is used - https://oss.sonatype.org/content/repositories/snapshots/com/squareup/spoon/spoon-runner/2.0.0-SNAPSHOT/spoon-runner-2.0.0-20181002.234303-49.pom.

This `kotlin-argparser` dep is located in maven central - https://central.sonatype.dev/artifact/com.xenomachina/kotlin-argparser/2.0.7/versions.

**Comment by cristiantanas** [comment]
@jaredsburrows thanks for the reply.

Actually, the `spoon-runner-2.0.0-SNAPSHOT` version references version **2.0.0** of the kotlin-argparser
```
<dependency>
   <groupId>com.xenomachina</groupId>
   <artifactId>kotlin-argparser</artifactId>
   <version>2.0.0</version>
   <scope>runtime</scope>
</dependency>
```

but I do not see this version on maven central... the one you are referencing is version **2.0.7** and the oldest available is 2.0.5.

I don't know if I am missing something here 🤔

**Comment by ivzb** [comment]
I'm experiencing the same issue. Is there any progress or workaround?

**Comment by gvignesh493** [comment]
@jaredsburrows any update on this issue ?

**Comment by IamVigneshG** [comment]
Any update on this ? @jaredsburrows

**Comment by jaredsburrows** [comment]
This is fixed locally and I published a new snapshot.
