### ISSUE TITLE
How to specify the APK?

### ISSUE THREAD

**Issue by eric-grab** [jaredsburrows/gradle-spoon-plugin#15]
This is because I want to use multiple APKs.

My project has a settings that caused `com.android.ddmlib.InstallException: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113` but I don't have the authority to remove/ change that settings

Using multiple APKs as follows:
```
splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk true
        }
    }
```
makes `./gradlew connectedAndroidTest` work again (it's using the `*-univeral-*.apk`).
Unfortunately, `./gradlew spoon` is not picking up the `*-univeral-*.apk`.

Is there any way I can specify the APK file for my tests?
This is definitely not your library's problem, just asking for any existing feature I'm not aware of or suggesting new feature here 😄  @jaredsburrows

**Comment by jaredsburrows** [comment]
I am wondering if the "testVariants" API from the Android gradle plugin is not returning the APK split? Also, this project is still relying on Spoon 2 SNAPSHOT as they have not released it.

**Comment by jaredsburrows** [comment]
@eric-grab How have you been working around this?

**Comment by jaredsburrows** [comment]
Any update?

**Comment by jaredsburrows** [comment]
Closing because there is no reply.
