### ISSUE TITLE
How to make a screenshot ?

### ISSUE THREAD

**Issue by Sancher17** [jaredsburrows/gradle-spoon-plugin#17]
I don't understand how to make a screenshot, plugin doesn't do it ?

I tried add it
`Spoon.screenshot(activity, "initial_state");`
but it doesn't work, because no import Spoon (import com.squareup.spoon.Spoon; - don't work) 

What I should to do?

**Comment by Sancher17** [comment]
I understood how to do it

here is code

`@RunWith(AndroidJUnit4.class)
public class MainActivityTest {

    @Rule
    public final SpoonRule spoon = new SpoonRule();
    @Rule
    public final ActivityTestRule<MainActivity> activityRule = new ActivityTestRule<>(MainActivity.class);

    @Test
    public void testMethod() throws Exception {
        
        spoon.screenshot(activityRule.getActivity(), "start");`

Why you don't write it in the readme?

**Comment by ripunjayasaran** [comment]
The above spoon screenshot approach did not work all the time for me. I think this feature is a bit broken on Spoon 2+ which is why he might not have mentioned it in the readme file.

**Comment by jaredsburrows** [comment]
@Sancher17 is correct but I do agree that @ripunjayasaran is right about the stability.
