### ISSUE TITLE
Running all the tests from androidTest

### ISSUE THREAD

**Issue by satyaattili** [jaredsburrows/gradle-spoon-plugin#19]
Thanks for the plugn for spoon

I am facing issue while running tests, provided className in the spoon gradle configuration. 
But all the tests under androidTest running.

`spoon {
    title = "Sanity tests"
    debug = true
    noAnimations = true
    adbTimeout = 5
    
    //instrumentationArgs = ["package=com.*.*.sanity"]
    className = "com.*.*.sanity.MyTest"

    /*if (project.hasProperty("spoonClassName")) {
        className = project.spoonClassName

        if (project.hasProperty("spoonMethodName")) {
            methodName = project.spoonMethodName
        }
    }*/

    grantAll = true
    shard = true
    numShards = 10
    shardIndex = 2

}`

i can see the log as below,
Running am instrument -w -r   -e shardIndex 0 -e numShards 2 -e log true -e class 'com.*.*.sanity.MyTest' com.*.*.test/android.support.test.runner.AndroidJUnitRunner on samsung-sm

The parameter from the command is as expected, but running all the tests under androidTest

running below command : 
./gradlew spoon<BuildFlavour>

What may be the issue?. Is it bug?

Below versions used in my Gradle.

apply plugin: "com.jaredsburrows.spoon"
classpath "com.jaredsburrows:gradle-spoon-plugin:1.3.0"
androidTestCompile "com.squareup.spoon:spoon-client:2.0.0-SNAPSHOT"

repos's
 maven { url "https://oss.sonatype.org/content/repositories/snapshots" }

Thanks

**Comment by ripunjayasaran** [comment]
You are using the wrong command which is why all your tests are running instead of a specific test. If you want to run a specific test, then you need to use this:
```
./gradlew spoon -PspoonClassName=com.package.blah.blah.ClassName
    -PspoonMethodName=testName
```

**Comment by satyaattili** [comment]
Thanks for your reply, in the gradle script className hardcoded. I think in that way also it should work right. 

`spoon {
    title = "Sanity tests"
    debug = true
    noAnimations = true
    adbTimeout = 5
    className='com.*.*.MyClassTest'
}`

**Comment by jaredsburrows** [comment]
@satyaattili I do not believe `className` supports regex. You need the fully qualified class name.

**Comment by jaredsburrows** [comment]
@satyaattili Were you able to get this working on your end?

**Comment by jaredsburrows** [comment]
Closing since there is no reply.

**Comment by satya-hike** [comment]
Sorry, for the delay in reply.. 
Changed my gradle variants. by using tag from parameters, selecting the android test flavours.
However, Not using this for now. 

I have set of test cases which takes 32 mins for run on single device. 
I used spoon and given 4 shrads to distribute my tests. Tests distributing between devices but the execution time was same as single device run.

So, we blocked here and working towards reason for this. Any Idea?

**Comment by satyaattili** [comment]
Sorry, for the delay in reply.. 
Changed my build gradle variants. by using tag from parameters, selecting the android test flavours. However, Not using spoon for now.  I have set of test cases which takes 32 mins for run on single device. I used spoon and given 4 shrads to run, Yes, tests distributing among devices but still the execution time is same as single run.

**Comment by jaredsburrows** [comment]
Alright. @satyaattili let me know how I can help if it pertains to this Gradle plugin.
