### ISSUE TITLE
Only one screenshot saved / added to report

### ISSUE THREAD

**Issue by fweigl** [jaredsburrows/gradle-spoon-plugin#2]
I use your version of the spoon plugin `com.jaredsburrows:gradle-spoon-plugin:1.1.11-SNAPSHOT` with the client `com.squareup.spoon:spoon-client:1.7.1`. 

I can run `./gradlew spoonDebug`, tests are run and a report is created. 
Unfortunately though, the report contains only the last screenshot taken; looking at the device folder `/sdcard/app_spoon-screenshots/...`, after running the tests, there is also only one screenshot saved. 

I have created an example project [here](https://github.com/fweigl/SpoonExample) that exhibits the problem. 

The output of gradle is [here](https://pastebin.com/qMveEyBa). 

Any idea how to fix this?

**Comment by tinsukE** [comment]
This plugin does make use of spoon 2.0.0-SNAPSHOT, have you tried using the matching spoon-client as suggested in the README?
`"com.squareup.spoon:spoon-client:2.0.0-SNAPSHOT"`

**Comment by hram** [comment]
@tinsukE I'm using "com.squareup.spoon:spoon-client:2.0.0-SNAPSHOT" but have error 

> Cannot resolve symbol 'Spoon'

**Comment by tinsukE** [comment]
To take screenshots with Spoon 2 you should use SpoonRule:
https://github.com/square/spoon/blob/master/spoon-client/src/main/java/com/squareup/spoon/SpoonRule.java

**Comment by jaredsburrows** [comment]
@fweigl I am very sorry. I have not received any emails regarding your issue!

**Comment by jaredsburrows** [comment]
@fweigl It is because it is putting everything into a separate test call. See https://github.com/stanfy/spoon-gradle-plugin/pull/161#issuecomment-346645943.

You have to specify `singleInstrumentationCall = true` in the DSL. Example:

```
spoon {
  singleInstrumentationCall = true
}
```

**Comment by fweigl** [comment]
Thanks for your comments guys. I'm having a hard time making my simple sample work. 
I've added to my dependencies: 
```
    androidTestImplementation 'com.squareup.spoon:spoon-client:2.0.0-SNAPSHOT'
    androidTestImplementation 'com.squareup.spoon:spoon-runner:2.0.0-SNAPSHOT'
```
and to the `android` block: 

```
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
```

This yields: 

> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForDebugAndroidTest'.

> Caused by: com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24

As a fix for that exception, [stackoverflow suggests](https://stackoverflow.com/questions/46754337/default-or-static-interface-method-used-without-min-sdk-version-24) to add `android.enableD8=true` to `gradle.properties`; doing this then results in: 

> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'.

> Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: org.apache.maven.reporting.MavenMultiPageReport

Does any of you guys maybe have a working setup ready somewhere for me to take a look at?

Thanks for your help.

**Comment by jaredsburrows** [comment]
You do not need Java 8.

```
buildscript {
  repositories {
    jcenter()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" } // For Spoon snapshot, until 2.0.0 is released
  }

  dependencies {
    classpath "com.jaredsburrows:gradle-spoon-plugin:1.1.0"
  }
}

apply plugin: "com.android.application"
apply plugin: "com.jaredsburrows.spoon"
```
and
```
repositories {
  jcenter()
  maven { url "https://oss.sonatype.org/content/repositories/snapshots" } // For Spoon snapshot, until 2.0.0 is released
}

dependencies {
  androidTestCompile "com.squareup.spoon:spoon-client:2.0.0-SNAPSHOT"
}
```

**Comment by fweigl** [comment]
When not explicitly importing the 2.0.0.SNAPSHOT of the runner, I get: 

> Caused by: java.lang.NoSuchMethodError: com.squareup.spoon.SpoonRunner$Builder.setTestApk(Ljava/io/File;)Lcom/squareup/spoon/SpoonRunner$Builder;
>         at com.jaredsburrows.spoon.SpoonTask.spoonTask(SpoonTask.kt:42)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

What am I missing there?

**Comment by jaredsburrows** [comment]
So are you saying if you add it as a dependency, it works? `spoon-client` is meant for the `androidTestCompile` configuration and `spoon-runner` is meant for the `classpath`.

Maybe the readme should be:

```
buildscript {
  repositories {
    jcenter()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" } // For Spoon snapshot, until 2.0.0 is released
  }

  dependencies {
    classpath "com.squareup.spoon:spoon-runner:2.0.0-SNAPSHOT" // For Spoon snapshot, until 2.0.0 is released
    classpath "com.jaredsburrows:gradle-spoon-plugin:1.1.0"
  }
}

apply plugin: "com.android.application"
apply plugin: "com.jaredsburrows.spoon"
```
and
```
repositories {
  jcenter()
  maven { url "https://oss.sonatype.org/content/repositories/snapshots" } // For Spoon snapshot, until 2.0.0 is released
}

dependencies {
  androidTestCompile "com.squareup.spoon:spoon-client:2.0.0-SNAPSHOT"
}
```

**Comment by dweebo** [comment]
Seems to me that this plugin should have a dependency on the spoon-runner, in order to make sure the correct version of the spoon-runner is there for this plugin.  Otherwise you run into issues like this.  If users want the ability to specify a specific spoon-runner for some reason they should be able to override what the plugin gives in their build.gradle right?

From @fweigl's comment it looks like without explicitly pulling down 2.0.0 it is using a non-2.0.0 version of the runner, that error message looks familiar from my work on the stanfy plugin, because 2.0.0 changed from `setInstrumentationApk ` to `setTestApk`.

**Comment by jaredsburrows** [comment]
@dweebo This plugin does have a dependency on the `spoon-runner`. See here: https://github.com/jaredsburrows/gradle-spoon-plugin/blob/master/build.gradle#L39.

**Comment by dweebo** [comment]
Ahh good point :) What does latest.integration pull down?  Maybe it isn't pulling the 2.0.0 snapshot?

**Comment by fweigl** [comment]
@jaredsburrows 
>So are you saying if you add it as a dependency, it works?
No, then I run into the problems I described above (gradle asking for Java 1.8 compile options, then the SimException). 

I've completely cleaned the gradle caches. 

You put the lines: 
```
apply plugin: "com.android.application"
apply plugin: "com.jaredsburrows.spoon"
```
in the first code block of your example `build.gradle` files. This somewhat implies they should be in the top-level `build.gradle`, I assume you didn't mean that?

So to confirm I have my build files in order, my top level build file being: 

```
buildscript {
    
    repositories {
        google()
        jcenter()
        maven { url "https://oss.jfrog.org/artifactory/oss-snapshot-local/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "com.jaredsburrows:gradle-spoon-plugin:1.1.0"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
Any my module build file being: 

```
apply plugin: "com.android.application"
apply plugin: "com.jaredsburrows.spoon"

repositories {
    jcenter()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" } // For Spoon snapshot, until 2.0.0 is released
}

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.spoonexample"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    spoon {
        singleInstrumentationCall = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    androidTestCompile 'com.squareup.spoon:spoon-client:2.0.0-SNAPSHOT'
}
```
Is that correct so far?

**Comment by jaredsburrows** [comment]
@dweebo I am using this in a project and it works and I am not seeing this problem. I just made this PR to run Spoon on the CI: https://github.com/jaredsburrows/gradle-spoon-plugin/pull/10.

@fweigl This is the problem: `classpath "com.jaredsburrows:gradle-spoon-plugin:1.1.0"` You are using a version that does not have the latest Spoon snapshot. I will release `1.2.0-SNAPSHOT` soon.

**Comment by jaredsburrows** [comment]
I just released `1.2.0`.

**Comment by fweigl** [comment]
Yeah, all working now, thanks a lot! :)

**Comment by jaredsburrows** [comment]
@fweigl Thank you for reporting issues!
