### ISSUE TITLE
JUnit XML generation is not as expected

### ISSUE THREAD

**Issue by nareshgunda-007** [jaredsburrows/gradle-spoon-plugin#21]
After integrating with this plugin, observed that jUnit xml generation is not as expected. Let say if i run 10 test cases in a package, generated junit xml file has only one test case and not all the 10 test cases. Is it a known-issue or im i missing something??

**Comment by thelittlefireman** [comment]
i thinks this will be fixed by this PR : [https://github.com/square/spoon/pull/519](https://github.com/square/spoon/pull/519)

**Comment by jaredsburrows** [comment]
Yeah, just waiting for the Spoon guys to merge it into master.

**Comment by jaredsburrows** [comment]
@nareshgunda-007, this is now merged, can you try again?

**Comment by jaredsburrows** [comment]
Any update @nareshgunda-007?

**Comment by jaredsburrows** [comment]
Closing since square/spoon#519 was merged.
