### ISSUE TITLE
Spoon crash on Jenkins

### ISSUE THREAD

**Issue by hannesa2** [jaredsburrows/gradle-spoon-plugin#22]
We see a lot of this in our Jenkins, has someone a clue what's wrong here ?
Any hint is helpful !
```
:app:spoonDebugAndroidTestException in thread "Device List Monitor" java.lang.NullPointerException
	at com.android.ddmlib.EmulatorConsole.checkConnection(EmulatorConsole.java:319)
	at com.android.ddmlib.EmulatorConsole.getConsole(EmulatorConsole.java:233)
	at com.android.ddmlib.DeviceMonitor.queryAvdName(DeviceMonitor.java:246)
	at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:218)
	at com.android.ddmlib.DeviceMonitor.access$400(DeviceMonitor.java:56)
	at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.java:658)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.processIncomingDeviceData(DeviceMonitor.java:843)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.run(DeviceMonitor.java:777)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jaredsburrows** [comment]
I am not sure what this is. Have you tried: https://stackoverflow.com/questions/43266321/reactnative-build-for-android-just-freezes-over-the-last-step?

**Comment by jaredsburrows** [comment]
I believe this has to do with your emulators?

**Comment by jaredsburrows** [comment]
Have you had a chance to review this?

**Comment by hannesa2** [comment]
We see it on Jenkins, it has 4 executors. This means we can run 4 emulators on the same time, so I can't restart `adb` as suggested there. I guess this would break the other running builds

As I saw you use spoon snapshot and we made a commit in spoon, to update used ddm version to `com.android.tools.ddms:ddmlib:26.0.1` https://github.com/square/spoon/commit/b4d6d85a1114377d338834d0fe501fd5314ca211 

So I made a test and fork your lib using this new spoon snapshot 
https://github.com/hannesa2/gradle-spoon-plugin/tree/UpdatedSpoon and we use now this updated gradle plugin
https://jitpack.io/#hannesa2/gradle-spoon-plugin/UpdatedSpoon-400e754243-1

```
dependencies {
   compile 'com.github.hannesa2.gradle-spoon-plugin:com.jaredsburrows.spoon.gradle.plugin:UpdatedSpoon-400e754243-1'
}

```
but unfortunately we still have issues

**Comment by jaredsburrows** [comment]
You could have made a PR to this repo for `26.0.1` :)

**Comment by hannesa2** [comment]
Of course I can, but did you saw my changes ? https://github.com/hannesa2/gradle-spoon-plugin/commit/400e754243523fcfc861971c9e1cdd96f6bf5730 
It was an empty commit, just to get new snapshot from spoon.

it can be done by `git commit -m "dummy/empty commit" --allow empty`

**Comment by hannesa2** [comment]
Btw it's related to our issues
https://issuetracker.google.com/issues/73641481
https://issuetracker.google.com/issues/72428322

**Comment by jaredsburrows** [comment]
As long as I am pointing to the snapshot, you should see it download the latest. I have already tested this.
