### ISSUE TITLE
Cannot import Spoon 2.0

### ISSUE THREAD

**Issue by szaske** [jaredsburrows/gradle-spoon-plugin#26]
I'm having a hell of a time getting Spoon 2.0 loaded and working.  I'm hoping you can help me troubleshoot the issue.

**Issue #1:**  I can get Gradle 4.1, your plugin and Spoon 1.7.1 working.  I have 3 UI tests, and in each I ask for a screenshot.  When I run the UI test alone I takes all 3 screenshots saved to the VM.  When I run the test through Spoon however it seems to save the last screenshot only.  I suspect that Spoon is overwriting the other screen shots, I'd like to debug Spoon however...

**Issue #2:**  I cannot seem to get Spoon to run in debug mode.  I've tried setting 'debug=true' in the Spoon config area, but that does not seem to make any difference, there or not I cannot get Spoon to run and stop at any breakpoint I'd included.

**Issue #3:**  I'm using Gradle 4.1, and wanted to get started using Spoon, but saw that the standard plugin, stanfy/spoon-gradle-plugin doesn't work with Gradle 4.x.  Then I saw you're post that you apparently got it working, but when I follow your instructions Android Studio and Gradle seem to load everything, but when I attempt to use spoon in my tests I get an error on the import.

"Cannot resolve Spoon".  
it cannot find the last 'Spoon' section of  the 'import com.squareup.spoon.Spoon' and hence, my code:

`Spoon.screenshot(getCurrentActivity(), tag);`

is also broken.  If I switch to using spoon-client:1.7.1 I no longer get issue #3, but I still have issues #1 and #2.

I'm just trying to figure out why Spoon is not saving my screenshots and I was hoping perhaps v2 would solve my problem...but then I cannot get v2 loaded...which is why I'm posting my troubles here.  Hope this all makes sense.

**Comment by markcerqueira** [comment]
Try using an instance of `SpoonRule()` for taking screenshots. 

That said, I can't get my setup to get proper permissions to save the screenshots.

**Comment by jaredsburrows** [comment]
@szaske 

1. This plugin is specifically for Spoon 2 AGP 3.0+.
2. 
3. `stanfy/spoon-gradle-plugin` has not updated their plugin in a long time. That is for Spoon 1.7.1 + < AGP 3.0.

@markcerqueira is right, you need to use `SpoonRule` from Spoon 2.
