### ISSUE TITLE
Update readme to mention using in library modules

### ISSUE THREAD

**Issue by tir38** [jaredsburrows/gradle-spoon-plugin#27]
[Buried down in the source](https://github.com/jaredsburrows/gradle-spoon-plugin/blob/master/src/main/kotlin/com/jaredsburrows/spoon/SpoonPlugin.kt#L45) is an indication that this plugin can also run Spoon on android **library** modules. After testing myself by adding plugin and `androidTestCompile` dependency to library's build.gradle,  I see that it works and generates additional Spoon report. This is a BFD. People have asked for it on [Spoon directly](https://github.com/square/spoon/issues/263) and on the other [Spoon plugin](https://github.com/stanfy/spoon-gradle-plugin/issues/13). There should be a little blurb in the README that this works. Nobody would ever discover this feature unless they went digging in the source.

**Comment by jaredsburrows** [comment]
@tir38 Nice find. Do you mind sending a PR?
