### ISSUE TITLE
Sqaureup Spoon-Runner still using XenoMachina:Kotlin-Parser:2.0.0

### ISSUE THREAD

**Issue by JManikiza** [jaredsburrows/gradle-spoon-plugin#324]
Tried:
'Sync Project with Gradle Files' with gradle-spoon-plugin/1.6.0 build && gradle-spoon-plugin/master build
./gradlew clean
./gradlew install

A problem occurred configuring root project 'cp-bluebox.android'.

Could not resolve all artifacts for configuration ':classpath'.
Could not find com.xenomachina:kotlin-argparser:2.0.0.
Searched in the following locations:
- file:/Users/USER/.m2/repository/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
- https://dl.google.com/dl/android/maven2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
- https://repo.maven.apache.org/maven2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
- https://oss.sonatype.org/content/repositories/snapshots/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
- https://plugins.gradle.org/m2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
- https://jitpack.io/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
- https://pkgs.dev.azure.com/COMPANY/COMPANY/_packaging/Libraries/maven/v1/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
Required by:
project : > com.github.jaredsburrows:gradle-spoon-plugin:master > com.github.jaredsburrows.gradle-spoon-plugin:gradle-spoon-plugin:master > com.squareup.spoon:spoon-runner:2.0.0-SNAPSHOT:20181002.234303-49

Thank you!

**Comment by jaredsburrows** [comment]
This is fixed here: https://github.com/jaredsburrows/gradle-spoon-plugin/issues/121#issuecomment-2260898685. I just have to make a release.

**Comment by JManikiza** [comment]
Thanks a bunch! 

it must have slipped my sight when I looked haha 

Take care
