### ISSUE TITLE
Could not find com.xenomachina:kotlin-argparser:2.0.0.

### ISSUE THREAD

**Issue by mrutyunjaypowerschool** [jaredsburrows/gradle-spoon-plugin#345]
A problem occurred configuring root project 
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.xenomachina:kotlin-argparser:2.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://repo.maven.apache.org/maven2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://jcenter.bintray.com/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://jitpack.io/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
       - https://plugins.gradle.org/m2/com/xenomachina/kotlin-argparser/2.0.0/kotlin-argparser-2.0.0.pom
     Required by:
         project : > com.jaredsburrows:gradle-spoon-plugin:1.6.0 > com.squareup.spoon:spoon-runner:2.0.0-SNAPSHOT:20181002.234303-49

I've recently encountered this issue. Is there any solution? If so, could you elaborate on the necessary changes to resolve it?

**Comment by jaredsburrows** [comment]
This is fixed here: https://github.com/jaredsburrows/gradle-spoon-plugin/issues/121#issuecomment-2260898685. I just have to make a release.

**Comment by mrutyunjaypowerschool** [comment]
Please release
