### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by ZakTaccardi** [jaredsburrows/gradle-spoon-plugin#35]
I'd like pass command line parameters.

```
./gradlew :app:spoonDebugAndroidTest -PspoonClassName=my_package.MyTestClass
```

Is this supported?

**Comment by handstandsam** [comment]
It would be helpful to provide which serial numbers to run the tests on at execution time without modifying the gradle script. This is possible via Spoon 2.0 with `--serial emulator-5558`.

**Comment by jaredsburrows** [comment]
@ZakTaccardi This only works if you setup those gradle properties. For instance, `spoonClassName`:
```
spoon {
  if (project.hasProperty('spoonClassName')) {
    className = project.spoonClassName  
  }
}
```

@handstandsam See the usage here: https://github.com/jaredsburrows/gradle-spoon-plugin#usage.

**Comment by ZakTaccardi** [comment]
@jaredsburrows would be nice is this lib was updated to automatically look for those parameters
