### ISSUE TITLE
Issue while executing Cucumber Scenarios.

### ISSUE THREAD

**Issue by AnubalaVashisht** [jaredsburrows/gradle-spoon-plugin#38]
I'm using Cucumber BDD Framework with spoon. During execution with spoon my scenarios are running in loop. All scenarios are getting executed multiple times sequentially. But in report it is being shown once only though screenshots for multiple executions are getting attached.

**Comment by TharianTom** [comment]
@AnubalaVashisht : I am not even able start a single test with cucumber-jvm and spoon. I am getting a parsing error at:
RemoteAndroidTest: Running am instrument -w -r   -e coverageFile /storage/emulated/legacy/coverage.ec -e class Feature Test Feature#Scenario Testing a feature -e coverage true -e foo bar com.cucumber.runners/com.cucumber.runners.Instrumentation on device

How do you change the class value here?

**Comment by AnubalaVashisht** [comment]
@TharianTom i didn't change any class value. Just running the features using below command:
/gradlew clean spoonProdDebugAndroidTest -PcucumberOptions="--tags @PS_Sanity"

**Comment by TharianTom** [comment]
@AnubalaVashisht  I am not specifying any class just ./gradlew spoon.
If its not too much trouble could you share your spoon task?

**Comment by lsuski** [comment]
The same for me. Problem appears when executing more than one cucumber scenario. It loops through all executed scenarios several times. `connectedAndroidTest` works fine

**Comment by lsuski** [comment]
The problem is in way spoon executes tests. Firstly it queries for tests and receives from cucumber list of scenarios, and then it executes `am instrument -w -r   -e class '<name of scenario>'` which for Cucumber does not make sense

**Comment by lsuski** [comment]
`singleInstrumentationCall = true` should solve the problem

**Comment by jaredsburrows** [comment]
@lsuski Did `singleInstrumentationCall = true` solve the problem @AnubalaVashisht?

**Comment by lsuski** [comment]
It solved for me. New version of cucumber-android should support test sharding with spoon. I think that this issue can be closed because it is cucumber-android issue

**Comment by jaredsburrows** [comment]
Thanks
