### ISSUE TITLE
Code Coverage not merging properly

### ISSUE THREAD

**Issue by kubovy** [jaredsburrows/gradle-spoon-plugin#39]
When running Spoon Tests with

    spoon {
        codeCoverage = true
    }

the merged-coverage.ec contains only results from one test case.

**Comment by jaredsburrows** [comment]
Are you setting test coverage for your `buildTypes`?
```
android {
  buildTypes {
    debug {
      testCoverageEnabled = true
    }
  }
}
```

**Comment by jaredsburrows** [comment]
This is a spoon related problem. This project is just to wrap Square's Spoon v2 in a Gradle plugin.

**Comment by michael-mohemian** [comment]
@jaredsburrows @kubovy did you track an issue at https://github.com/square/spoon?

**Comment by jaredsburrows** [comment]
I am not sure. I also do not believe this is actively being worked on by Square anymore.

There is also a new API from Google to take screenshots for your UI/Espresso tests.
