### ISSUE TITLE
Wrong spoon-output folder

### ISSUE THREAD

**Issue by Yukooo** [jaredsburrows/gradle-spoon-plugin#4]
I have two flawors xxx and yyy,
as a result I have two gradle tasks:  `spoonXxxDebugAndroidTest` &  `spoonYyyDebugAndroidTest`
When I run `app:spoonXxxDebugAndroidTest` at the end I have the `index.html` in the folder
`/app/build/spoon-output/yyyDebug/xxxDebug/index.html`
It is wrong because it should be 
`/app/build/spoon-output/xxxDebug/index.html`

And If I want to run the `spoonYyyDebugAndroidTest` then
`/app/build/spoon-output/yyyDebug/index.html`

**Comment by jaredsburrows** [comment]
@Yukooo  I am very sorry. I have not received any emails regarding your issue!

**Comment by jaredsburrows** [comment]
@Yukooo I believe I solved this here: https://github.com/jaredsburrows/gradle-spoon-plugin/commit/7030f27634da5c8666c53a918de0278a45e2f8f8.

**Comment by jaredsburrows** [comment]
@alexilyenko confirmed my fix, I am closing this issue now.
