### ISSUE TITLE
Last test erase the screenshot of the first test

### ISSUE THREAD

**Issue by chimanos** [jaredsburrows/gradle-spoon-plugin#43]
Hello guys,
I think I have a problem with the screenshot when I run multiple tests.

I have 3 tests:
```
@Test
public void testOne() throws InterruptedException {
        Espresso.onView(withId(R.id.home_edit_ref_ean)).perform(click(), replaceText("testOne"));
        FalconSpoon.screenshot(mHomeActivityRule.getActivity(), "test_a");
        Thread.sleep(1000);
}
```
```
@Test
public void testTwo() throws InterruptedException {
        Espresso.onView(withId(R.id.home_edit_ref_ean)).perform(click(), replaceText("testTwo"));
        FalconSpoon.screenshot(mHomeActivityRule.getActivity(), "test_b");
        Thread.sleep(1000);
}
```
```    
@Test
public void testThree() throws InterruptedException {
        Espresso.onView(withId(R.id.home_edit_ref_ean)).perform(click(), replaceText("testThree"));
        FalconSpoon.screenshot(mHomeActivityRule.getActivity(), "test_c");
        Thread.sleep(1000);
}
```

The screenshot of the TestOne and TestTwo are not save. Only screenshot of the test Three are save. 
It's like the TestThree screenshot erase the screenshot of the two first tests.

Screenshot of the result here: [Here](http://www.zupimages.net/viewer.php?id=18/31/zk88.png)

Do you have an idea about this issue ? 

Thank you guys :)

**Comment by jaredsburrows** [comment]
I am currently not seeing this in the test app in this repo.
<img width="1371" alt="Screen Shot 2022-04-24 at 4 44 42 PM" src="https://user-images.githubusercontent.com/1739848/164995872-0f9e5333-f16b-4240-8d15-381344aaca3f.png">
