### ISSUE TITLE
Impossible to set clearAppDataBeforeEachTest in gradle file

### ISSUE THREAD

**Issue by Sianay** [jaredsburrows/gradle-spoon-plugin#44]
When adding `clearAppDataBeforeEachTest` in gradle 

```
spoon {
    clearAppDataBeforeEachTest = true
}
```

I got this error at sync: 

`Could not set unknown property 'clearAppDataBeforeEachTest' for object of type com.jaredsburrows.spoon.SpoonExtension.`

**Comment by QAutomatron** [comment]
Try to use Snapshot version of plugin `1.4.1-SNAPSHOT`.

**Comment by QuirijnGB** [comment]
I'm having the same issue, tried on `1.4.0`, `1.4.1-SNAPSHOT` and `2.0.0-SNAPSHOT`

**Comment by QAutomatron** [comment]
@QuirijnGB try to use snapshot version of plugin not the Spoon client. `com.jaredsburrows:gradle-spoon-plugin:1.4.1-SNAPSHOT`

**Comment by jaredsburrows** [comment]
@QAutomatron Maybe I did not release this yet? Should I make another release?

**Comment by QAutomatron** [comment]
@jaredsburrows may be, but it works for me if I use snapshot of plug-in, the version I mentioned above.

**Comment by jaredsburrows** [comment]
@Sianay @QAutomatron I have released `1.5.0`, along with `1.5.1-SNAPSHOT`. Please let me know if you see this issue again.
