### ISSUE TITLE
SpoonPlugin.kt - Two deprecation warnings with Android Gradle Plugin 3.3

### ISSUE THREAD

**Issue by vladad** [jaredsburrows/gradle-spoon-plugin#48]
Now is build with Android Studio 3.3 successful, but deprecation warning is displayed:

1. variant.getAssemble()

`13:54:28.610 [WARN] [org.gradle.api.Project] WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1559)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.BaseVariantImpl.getAssemble(BaseVariantImpl.java:571)
com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getAssemble(null:-1)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:41)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:12)
...
...`

2. variantOutput.getPackageApplication()

`13:54:28.614 [WARN] [org.gradle.api.Project] WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1559)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.ApkVariantOutputImpl.getPackageApplication(ApkVariantOutputImpl.java:57)
com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getPackageApplication(null:-1)
com.android.build.gradle.internal.api.ApkVariantOutputImpl.getOutputFile(ApkVariantOutputImpl.java:68)
com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getOutputFile(null:-1)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:42)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:12)
...
...`

Thanks.

**Comment by lernerb** [comment]
Hey @jaredsburrows, also seeing this warning come up. Running this command points back to this dependency. Need help on this one?

`./gradlew clean --stacktrace -Pandroid.debug.obsoleteApi=true`

```
WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1559)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.BaseVariantImpl.getAssemble(BaseVariantImpl.java:571)
com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getAssemble(null:-1)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:41)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:12)
org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1.execute(SpoonPlugin.kt:35)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1.execute(SpoonPlugin.kt:12)
org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:244)
org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:233)
com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:103)
com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:777)
com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
com.android.build.gradle.BasePlugin.lambda$createTasks$4(BasePlugin.java:651)
```

**Comment by jaredsburrows** [comment]
This is just a warning. If I remove this, it would break it lower versions of AGP + Gradle versions. If I want to support both, development becomes more painful.

I will look into update the min AGP version for this plugin.

**Comment by ZakTaccardi** [comment]
> If I remove this, it would break it lower versions of AGP + Gradle versions. If I want to support both, development becomes more painful.

One option would be to do an if-check based on the AGP version, if that's possible

> I will look into update the min AGP version for this plugin.

👍 👍

**Comment by ZakTaccardi** [comment]
I believe this is causing tasks to be configured too early for us, slowing down our builds.

I would simply release a new version that requires a min of 3.3 AGP. If consumers wish to use a version of AGP < 3.3 - can't they depend on an older version of the spoon plugin?

**Comment by viader** [comment]
Please provide some magic to rid this warning, it can turn into problem soon ~"It will be removed at the end of 2019."

**Comment by ZakTaccardi** [comment]
@jaredsburrows is there an update for this?

Supporting old versions of Gradle holds back Gradle as a build system. Using outdated dependencies is irresponsible development. If consumers of this lib are depending on < AGP 3.3 support, they can depend on an older version.

**Comment by jaredsburrows** [comment]
@ZakTaccardi I do not believe they have removed these methods. Are running into problems now? Once I do remove them, it will force users to upgrade their AGP plugins to a newer version.

**Comment by ZakTaccardi** [comment]
They have not been removed yet, but they will be. I don't understand the downside of requiring the plug-in to support AGP 3.3+.

If someone needs pre-AGP support, can't they depend on an older version of this spoon plug-in?

**Comment by jaredsburrows** [comment]
I didnt say anything about a downside. I just have not updated this plugin in a while. I am always open to PRs :). Yes, they can depend on an older version but wont be able to get any newer features.

https://github.com/jaredsburrows/gradle-spoon-plugin/blob/master/gradle/dependencies.gradle#L12
