### ISSUE TITLE
Test is not run in parallel on connected devices

### ISSUE THREAD

**Issue by endless-qa** [jaredsburrows/gradle-spoon-plugin#49]
Android Gradle plugin: **3.2.1**
Gradle Spoon plugin: **1.4.0**
Spoon settings: **default**
Android Studio: **3.2.1**
Environment: **macOS Mojave 10.14.1**

Description:
There are 2-3 devices connected to my setup. If I run tests via **./gradlew spoon[flavour]**, they are executed sequentially on each device, i.e. no parallelism. I have tried to play with different combination of Spoon settings (like sequential, shards, singleInstrumentationCall, etc.) but no luck. However, when I run the same tests just with **./gradlew connectedAndroidTest**, they are executed in parallel on all connected devices.

Any ideas?

**Comment by ripunjayasaran** [comment]
Did you set 'shard = true'  and 'numshards = your_preferred_number' in your build.gradle file?

**Comment by cdkakade** [comment]
I am also facing this issue

**Comment by jaredsburrows** [comment]
Can you post your `build.gradle`? Is this still an issue? Feel free to reopen.
