### ISSUE TITLE
Maven Repository is down

### ISSUE THREAD

**Issue by entrealist** [jaredsburrows/gradle-spoon-plugin#52]
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.squareup.spoon:spoon-runner:2.0.0-SNAPSHOT.
     Required by:
         project : > com.jaredsburrows:gradle-spoon-plugin:1.5.0
      > Could not resolve com.squareup.spoon:spoon-runner:2.0.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/squareup/spoon/spoon-runner/2.0.0-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/com/squareup/spoon/spoon-runner/2.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by caipivara** [comment]
Looks like it was something related to the moment you tried? now it is working

**Comment by jaredsburrows** [comment]
Closing this as this is not related to this project. The dependency we need is located on mavencentral.
