### ISSUE TITLE
Wrong snapshot reference in readme

### ISSUE THREAD

**Issue by jmlord** [jaredsburrows/gradle-spoon-plugin#56]
Hi,

This will not take much of your time!

Readme references following snapshot, which does not exist:
classpath 'com.jaredsburrows:gradle-spoon-plugin:**1.5.1**-SNAPSHOT'

Please update with the correct link:
classpath 'com.jaredsburrows:gradle-spoon-plugin:**2.0.0**-SNAPSHOT'

Thanks,
Jean-Michel

**Comment by lsuski** [comment]
Actually, the correct version is 1.5.1-SNAPSHOT but it is not published due to `/home/travis/.travis/functions: line 109: .buildscript/deploy-snapshot.sh: No such file or directory`

**Comment by jaredsburrows** [comment]
This was fixed in #87.
