### ISSUE TITLE
Spoon is slower than connectedPlaystoreDebugAndroidTest even running on multiple device

### ISSUE THREAD

**Issue by alphaguy4** [jaredsburrows/gradle-spoon-plugin#57]
Hi 
I am trying to run my instrumentation test using spoon on 2 device. However, it is taking 4x more time to execute those testcases. I have almost 10 packages containing total 2k testcases.
When running task `connectedPlaystoreDebugAndroidTest  ` it takes around 15mins on my system. However, when running `spoonPlaystoreDebugAndroidTest` it take 4 times the time and testcases are not even finished.

Gradle version - 5.1.1
Android Gradle Plugin version = 3.3.2
OS - macOS HighSierra 10.13.6
Number of devices - 2
Using the below setting

```
spoon {
    shard = true
}
```
I can see most of the time the device is idle. While running the tests intermittently on each devices. Sometimes together or sometimes sequentially.

Stuck on this. Can you help ?

**Comment by alphaguy4** [comment]
@jaredsburrows 
I can see from the console output it is actually taking time to execute each testcase one by one. However connectPlaystoreDebugAndroidTest is faster.

**Comment by alphaguy4** [comment]
@jaredsburrows Time gap between two testcases is very high when running test with spoon and hence overall time for execution increases by many folds.
What am i missing?

**Comment by alphaguy4** [comment]
@jaredsburrows I am able to run test using spoon jar while plugin isn't working properly.

**Comment by ZakTaccardi** [comment]
spoon using something similar to [Android Test Orchestrator](https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator) to run each test in a new process. This reduces flakiness, but increases test time. So if you are not using Orchestrator with your `connectedPlaystoreDebugAndroidTest`, then spoon test time will be much longer

**Comment by jaredsburrows** [comment]
@alphaguy4 Slower to run or to "finish"? Pulling the screenshots and generating the gifs. You can try turn this off:
```
spoon {
  noAnimations = true
}
```
