### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dweebo** [jaredsburrows/gradle-spoon-plugin#6]
Apache 2.0 probably since this project is in part a fork from the stanfy gradle-spoon-plugin

**Comment by jaredsburrows** [comment]
@dweebo I am very sorry. I have not received any emails regarding your issue!

**Comment by jaredsburrows** [comment]
Thanks! Here is the PR: https://github.com/jaredsburrows/gradle-spoon-plugin/pull/7.
