### ISSUE TITLE
noAnimations not working

### ISSUE THREAD

**Issue by mattcmf** [jaredsburrows/gradle-spoon-plugin#60]
I am trying to run tests with animations disabled via:
```
 spoon {
        debug = true
        noAnimations = true
        singleInstrumentationCall = true
        shard = true
        clearAppDataBeforeEachTest = true
    }
```

However it appeared animations were still being rendered.

Added TestButler to verify via:
`TestButler.verifyAnimationsDisabled();`

And as I assumed, it confirmed animations were not being disabled.

**Comment by jaredsburrows** [comment]
`noAnimations` disables the automatic GIF generation and not app animations.

See: https://github.com/square/spoon/blame/7252d7b88ba1e25469f9e9c69b00c37870ee7e15/README.md#L133.
