### ISSUE TITLE
compilation warning "WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'. It will be removed at the end of 2019"

### ISSUE THREAD

**Issue by pickeyboy** [jaredsburrows/gradle-spoon-plugin#77]
After upgrading gradle version to 3.5.3 and Kotlin version to 1.3.50 I started observing following warnings 

WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.

WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019

While investigating this warning further and compiling the code with option "-Pandroid.debug.obsoleteApi=true" I got following stacktrace

REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1556)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.ApkVariantOutputImpl.getPackageApplication(ApkVariantOutputImpl.java:57)
com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getPackageApplication(null:-1)
com.android.build.gradle.internal.api.ApkVariantOutputImpl.getOutputFile(ApkVariantOutputImpl.java:68)
com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getOutputFile(null:-1)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:42)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:12)
org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1.execute(SpoonPlugin.kt:35)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1.execute(SpoonPlugin.kt:12)
org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:247)
org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:236)
com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:97)
com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:720)
com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:82)
com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:615)
com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)
...
...

Looks like the warning appears to be from spoon plugin.

**Comment by ZakTaccardi** [comment]
this was fixed in https://github.com/jaredsburrows/gradle-spoon-plugin/pull/73 - just not release yet.

@jaredsburrows if you could kick of a release, that would be great :)

**Comment by pjakubczyk** [comment]
@jaredsburrows a kind ping :)

**Comment by BugsBunnyBR** [comment]
Can we have the release? It's been months since the PR was merged... It would give us time to migrate before the release of AGP 5.0...

**Comment by jaredsburrows** [comment]
Closing this since it was fixed in #73.

**Comment by jaredsburrows** [comment]
@ZakTaccardi @pjakubczyk @BugsBunnyBR Just released https://github.com/jaredsburrows/gradle-spoon-plugin/releases/tag/1.5.1 today.
