### ISSUE TITLE
I want to be able to run a custom version of spoon runner.

### ISSUE THREAD

**Issue by emathew80** [jaredsburrows/gradle-spoon-plugin#81]
Hey ya'll, 

Is there a way that I can run a custom version of spoon runner in gradle-spoon-plugin? It looks like yall are using the dependencies.gradle to set the spoon runner. I tried cloning your project replacing the spoon runner specified in the dependencies.gradle with a custom spoon runner jar that I adapted to meet my needs (I only want to log log.i statements in the html report). I created a .jar file from gradle-spoon-plugin imported it into my Android project added the dependency in the Android (project level) build.gradle

```
	dependencies {
		//Other dependencies here
		classpath files('libs/gradle-spoon-plugin-1.5.1-SNAPSHOT.jar')
	}
```

When I gradle sync after in adding the below to the app module build.gradle 
`
`apply plugin: 'com.jaredsburrows.spoon'`

I get an error:

```
Build file '/path/modulename/build.gradle' line: 230
A problem occurred evaluating project ':modulename'.
> Plugin with id 'com.jaredsburrows.spoon' not found.
```
` 
Any ideas how I could proceed or how I could just sub a custom version of the spoon runner for gradle-spoon-plugin?

**Comment by jaredsburrows** [comment]
You can try excluding the spoon artifact and adding your own manually. For example: https://stackoverflow.com/a/22365477/950427.
