### ISSUE TITLE
Leakcanary not detecting while running with spoonDebug command

### ISSUE THREAD

**Issue by IamVigneshG** [jaredsburrows/gradle-spoon-plugin#83]
While running from studio,my app getting detected by leakcanary for memory leaks. But if runned by spoon command from terminal, its not.

**Comment by jaredsburrows** [comment]
Do you have a `build.gradle` to show? Leakcanary would have to be added in your `debugImplementation` and potentially your `androidTestImplementation`. See https://square.github.io/leakcanary/upgrading-to-leakcanary-2.0/#now_4.
