### ISSUE TITLE
Ensure support for the new Gradle Configuration Cache

### ISSUE THREAD

**Issue by ZakTaccardi** [jaredsburrows/gradle-spoon-plugin#84]
Gradle has a new feature called the [Configuration Cache](https://docs.gradle.org/nightly/userguide/configuration_cache.html). It was previously known as Instant Execution, and this greatly improves build speed.

Usage of the Configuration Cache has a stricter list of [requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#requirements).

While this Gradle Plugin may already be compatible with the Configuration Cache, please investigate this to ensure support.

**Comment by jaredsburrows** [comment]
Do you know what changes are needed? I tried running `gradlew --configuration-cache help`, most of the issues seem to be not in my plugin but the plugins I am using.

**Comment by jaredsburrows** [comment]
Running `gradlew --configuration-cache help` shows no problems for `com.jaredsburrows.spoon`.

**Comment by eskatos** [comment]
@jaredsburrows it's a good step that means that the `spoon` plugin doesn't contain problematic code at configuration time.
What about running the task that the `spoon` plugin contributes?

**Comment by eskatos** [comment]
Yep I meant running `gradlew --configuration-cache spoonDebugAndroidTest` twice to exercise storing and loading the configuration cache with this task contributed to the task graph.

You can find an example of testing with TestKit here https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:testing

**Comment by jaredsburrows** [comment]
@eskatos released with configuration cache support in https://github.com/jaredsburrows/gradle-spoon-plugin/releases/tag/1.6.0.
