### ISSUE TITLE
JCenter end of life

### ISSUE THREAD

**Issue by nbonbon** [jaredsburrows/gradle-spoon-plugin#93]
JFrog announced that they'll be shutting down JCenter:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Key dates:
- February 28th: No more submissions will be accepted to Bintray, JCenter
- May 1st: Bintray, JCenter services will no longer be available

Hence gradle-spoon-plugin should also be migrated to another maven repository like Maven central.

**Comment by nicandris** [comment]
+1

**Comment by jaredsburrows** [comment]
I will publish a release soon.

**Comment by jaredsburrows** [comment]
Fixed here: https://github.com/jaredsburrows/gradle-spoon-plugin/commit/c6036263197165948348d7f78b77698c3f0b28ae.
