### ISSUE TITLE
Revert `upToDateWhen{ false }` removal

### ISSUE THREAD

**Issue by ZakTaccardi** [jaredsburrows/gradle-spoon-plugin#98]
This PR introduced incorrect incrementality: https://github.com/jaredsburrows/gradle-spoon-plugin/pull/92

Incrementality around running Android UI tests is tricky. You have to account for classpath changes and many other things.

For example, I ran a spoon test, which passed. Then I changed some code to alter the APK which gets built. I re-run the spoon task, and it was considered up to date. I would argue this is incorrect, and tests should have re-ran.

**Comment by jaredsburrows** [comment]
Removed here: https://github.com/jaredsburrows/gradle-spoon-plugin/commit/dfd6951724c22619d8013c6cac95d2238f9cca45.
